# Generated by Django 4.2.5 on 2023-09-11 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Inventory',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='BookingDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 11, 7, 17, 46, 698071)),
        ),
    ]
