# Generated by Django 4.2.5 on 2023-09-12 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_alter_booking_bookingdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='No_of_guests',
            new_name='no_of_guests',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='Inventory',
            new_name='inventory',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='BookingDate',
        ),
        migrations.AddField(
            model_name='booking',
            name='bookingDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 8, 4, 14, 656425)),
        ),
    ]
